# Cloudflare Workers Configuration
# Note: This project currently uses Express.js which requires Cloudflare Pages, not Workers
# This file is kept for future migration to Workers if needed

name = "report-sys"
main = "dist/worker-minimal.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "report-sys"
route = "report-sys.workers.dev/*"

# D1 Database configuration (for future use when migrating to Workers)
# [[d1_databases]]
# binding = "DB"
# database_name = "reportDB"
# database_id = "7fd6d73e-5311-497d-aa32-5b82cda99292"

# Note: build:worker script does not exist - use Cloudflare Pages instead
# [build]
# command = "npm run build:worker"